import type { Issue } from './types.js';

/**
 * The whole MVP build, except UI, as parallel issues. Source of truth for Linear, tasks/*.md and the CI ownership
 * check. Every issue can start immediately: contracts are frozen, every file already exists as a wired stub.
 */
const TA = 'services/tool-api/';
const CH = 'services/channels/';
const PV = 'services/provisioning/';
const PC = 'services/post-call/';
const CP = 'services/control-plane/';
const FD = 'engines/livekit-agent/';
const W = ['1145-lane-workflow'];
const vt = (dir: string) => `pnpm vitest run ${dir}`;

export const ISSUES: Issue[] = [
  // ───────────────────────────── contracts ─────────────────────────────
  { id: 'C0', title: 'Contracts and data-model steward', stream: 'contracts', agent: 'claude', priority: 1,
    owns: ['contracts/**', 'packages/shared/**', 'infra/cdk/lib/data-stack.ts', 'infra/cdk/lib/events-stack.ts'],
    skills: [...W, '1145-tenant-isolation', '1145-aws-cdk'],
    goal: 'Keep contracts frozen and coherent while ~50 agents build against them; process change requests within hours.',
    testsFirst: ['A test that every operationId in contracts/openapi/*.yaml maps to a handler file under services/ (route table in infra).', 'Event schema test: every EventType in packages/shared has a $defs entry.'],
    steps: ['Watch contracts/CHANGE_REQUESTS/; for each: accept (one PR updating contracts + packages/shared), or reject with a reason on the Linear issue.', 'Add request/response examples for every voice-path operation.', 'Never break a field after it is merged; add, deprecate, then remove in Phase 2.'],
    acceptance: ['No open change request older than 4 hours.', 'make test green; YAML/JSON contracts parse.'],
    testCmd: 'pnpm vitest run packages/shared' },

  // ───────────────────────────── platform ─────────────────────────────
  { id: 'P1', title: 'GitHub repo, rulesets, labels, environments', stream: 'platform', agent: 'devin', priority: 1,
    owns: ['scripts/github/**', '.github/rulesets/**', '.github/labels.json', '.github/CODEOWNERS', '.github/pull_request_template.md'],
    skills: [...W, '1145-ci-and-prs'],
    goal: 'Make the repo safe for 50 concurrent agent PRs: required checks, auto-merge, CODEOWNERS on contracts and IAM, dev/prod environments.',
    testsFirst: ['scripts/github/verify.sh that asserts (via gh api) the ruleset, required check names, auto-merge, delete-branch-on-merge, environments.'],
    steps: ['Run scripts/github/setup.sh against the repo (the owner provides GH_ADMIN_TOKEN).', 'Confirm required check names exactly match job names in .github/workflows/ci.yml and claude-review.yml.', 'If the plan lacks rulesets on private repos, fall back to classic branch protection and document it.', 'Enable merge queue if available (CI already listens to merge_group).'],
    acceptance: ['verify.sh passes.', 'A test PR with a failing check cannot merge; a green one auto-merges.'],
    testCmd: 'bash scripts/github/verify.sh' },
  { id: 'P2', title: 'AWS bootstrap, OIDC roles, deploy pipeline', stream: 'platform', agent: 'devin', priority: 1,
    owns: ['infra/cdk/bin/**', 'infra/cdk/lib/github-oidc-stack.ts', 'infra/cdk/lib/paths.ts', 'infra/cdk/lib/lambda.ts', 'infra/cdk/package.json', 'infra/cdk/cdk.json', 'infra/cdk/tsconfig.json', '.github/workflows/deploy.yml', 'scripts/secrets/**'],
    skills: [...W, '1145-aws-cdk', '1145-ci-and-prs'],
    goal: 'Every merge to main deploys to dev automatically via OIDC; prod promotion needs the owner\'s approval.',
    testsFirst: ['A CDK assertion test for GithubOidcStack: trust is limited to repo:<repo>:environment:<env> and aud sts.amazonaws.com.'],
    steps: ['cdk bootstrap dev and prod (owner runs the command you prepare).', 'Deploy ai1145-github-oidc with -c repo=<owner>/<repo>; store role ARNs as repo variables.', 'Make deploy.yml deploy all stacks on main, then call e2e.yml; prod job uses the protected environment.', 'scripts/secrets/push.sh: .env -> GitHub secrets and Secrets Manager (names from docs/API_KEYS.md).'],
    acceptance: ['A merged no-op PR deploys to dev within 20 minutes with no long-lived AWS keys in GitHub.'],
    testCmd: 'cd infra/cdk && pnpm tsc -p tsconfig.json' },
  { id: 'P3', title: 'CI checks, dependency lock, merge safety', stream: 'platform', agent: 'claude', priority: 1,
    owns: ['.github/workflows/ci.yml', '.github/workflows/automerge.yml', '.github/workflows/ci-failure-router.yml', '.github/workflows/claude-review.yml', '.github/workflows/claude.yml', 'scripts/ci/**', 'package.json', 'pnpm-lock.yaml', 'pnpm-workspace.yaml', 'tsconfig.json', 'tsconfig.base.json', 'vitest.config.ts', 'Makefile', '.mcp.json', '.cursor/mcp.json', 'engines/livekit-agent/uv.lock', 'agents/uv.lock'],
    skills: [...W, '1145-ci-and-prs'],
    goal: 'Required checks that are fast (<8 min), deterministic, and catch the failure modes of parallel agents: ownership drift, contract edits, lockfile fights, robotic prompts, red main.',
    testsFirst: ['Unit tests for scripts/ci/* (ownership, contract guard, PR tag parsing).'],
    steps: ['Own the lockfiles: batch dependency requests from CHANGE_REQUESTS into one PR per day.', 'Keep CI under 8 minutes with pnpm cache and parallel jobs.', 'Tune claude-review.yml so it blocks only on checklist violations, not style nits.', 'Verify ci-failure-router tags the right agent for Devin, Cursor and Claude PRs.'],
    acceptance: ['Median CI time < 8 min.', 'A PR touching a file outside its issue fails "ownership".', 'A PR editing contracts/ without the contract-change label fails.'],
    testCmd: 'pnpm vitest run orchestration scripts/ci' },
  { id: 'P4', title: 'CDK assertion tests for isolation and safety', stream: 'platform', agent: 'cursor-grok', priority: 2,
    owns: ['infra/cdk/test/**'], skills: [...W, '1145-aws-cdk', '1145-tenant-isolation'],
    goal: 'Lock in the security properties of the infrastructure so no later PR can silently weaken them.',
    testsFirst: ['TenantDataRole: dynamodb actions only with LeadingKeys TENANT#${aws:PrincipalTag/tenant_id}; trust has sts:TagSession.', 'No IAM statement grants dynamodb:* or s3:* on the tenant table/bucket without a condition.', 'Audit bucket has Object Lock; tenant bucket blocks public access and enforces SSL.', 'WhatsApp route absent unless enableWhatsApp=true.'],
    steps: ['Use aws-cdk-lib/assertions Template.fromStack on each stack.'], acceptance: ['Tests run in CI under the typescript job.'], testCmd: 'pnpm vitest run infra/cdk/test' },
  { id: 'P5', title: 'Cognito Google sign-in and pre-token trigger', stream: 'platform', agent: 'devin', priority: 1,
    owns: ['infra/cdk/lib/auth-stack.ts', 'services/auth/**'], skills: [...W, '1145-aws-cdk', '1145-tenant-isolation', '1145-channels-no-approval'],
    goal: 'Owners sign in with Google (openid email profile only, no Google review) and their tokens carry custom:tenant_id that users cannot edit.',
    testsFirst: ['pre-token handler: MEMBER# lookup sets custom:tenant_id/role; unknown user gets no tenant claim; suspended tenant still signs in but claim state=suspended.'],
    steps: ['Add UserPoolIdentityProviderGoogle with secret from Secrets Manager.', 'Hosted UI domain per stage; callback URLs for the owner PWA and localhost.', 'Document the Google OAuth client setup (scopes, authorized redirect URIs) in services/auth/README.md.'],
    acceptance: ['Sign-in works in dev with a real Google account; ID token contains custom:tenant_id after onboarding.'], testCmd: vt('services/auth') },
  { id: 'P6', title: 'AppSync Events publisher and channel authorization', stream: 'platform', agent: 'devin', priority: 1,
    owns: ['infra/cdk/lib/realtime-stack.ts', 'services/live-publisher/**'], skills: [...W, '1145-aws-cdk', '1145-tenant-isolation'],
    goal: 'Dashboard and owner chat get live events; nobody can subscribe to another tenant or owner.',
    testsFirst: ['publish(): masks phone numbers, drops internal fields, maps event -> /tenants/<tid>/live; owner chat replies -> /owners/<sub>/chat.', 'Integration test in dev: owner A cannot subscribe to /tenants/<B>/live.'],
    steps: ['Implement SigV4-signed HTTP publish to the AppSync Events endpoint.', 'Verify onSubscribe handlers deny cross-tenant/cross-owner subscriptions.'],
    acceptance: ['booking.created appears in a subscribed client within 1 s in dev.'], testCmd: vt('services/live-publisher') },
  { id: 'P7', title: 'Observability: dashboards and alarms', stream: 'platform', agent: 'devin', priority: 2,
    owns: ['infra/cdk/lib/observability-stack.ts', 'docs/runbooks/alarms.md'], skills: [...W, '1145-aws-cdk'],
    goal: 'The owner gets paged for failed calls, slow tools, DLQ messages and 5xx bursts, and can trace one call end to end.',
    testsFirst: ['CDK assertions: alarms exist for tool p95 > 300 ms, failed calls > 2/10 min, DLQ depth > 0, API 5xx.'],
    steps: ['Dashboard: calls, failures, tool latency per route, FIFO age, AgentCore errors, minutes by tenant.', 'Alarm topic subscription by email (no SMS in MVP).'],
    acceptance: ['An induced tool error in dev fires the alarm email.'], testCmd: 'pnpm vitest run infra/cdk/test' },
  { id: 'P8', title: 'End-to-end harness and the Gate scenario', stream: 'quality', agent: 'devin', priority: 1,
    owns: ['tests/e2e/harness/**', 'tests/e2e/scenarios/**', '.github/workflows/e2e.yml'], skills: [...W, '1145-ci-and-prs', '1145-conversation-style'],
    goal: 'After every dev deploy, prove the product works end to end, including that it sounds human.',
    testsFirst: ['The Gate scenario from docs/03-implementation-plan.md as an automated test (web chat via API, Telegram via Bot API test chat, phone via Telnyx outbound call to the tenant DID with scripted TTS caller).'],
    steps: ['tests/e2e is its own npm project (own lockfile, not in the pnpm workspace).', 'Run conversation-style checks on every agent turn captured in the scenario.', 'Post a summary comment on the merged PR and on the Linear project.'],
    acceptance: ['e2e.yml runs after deploy and fails the deployment status on a broken flow.'], testCmd: 'cd tests/e2e && npm test' },

  // ───────────────────────────── tool API ─────────────────────────────
  { id: 'T0', title: 'Tool API core maintainer (bookings, knowledge, handoff)', stream: 'tool-api', agent: 'claude', priority: 2,
    owns: [`${TA}src/handlers/create-booking.ts`, `${TA}src/handlers/check-availability.ts`, `${TA}src/handlers/lookup-caller.ts`, `${TA}src/handlers/take-message.ts`, `${TA}src/handlers/request-handoff.ts`, `${TA}src/handlers/search-knowledge.ts`, `${TA}src/lib/repo.ts`, `${TA}src/lib/slots.ts`, `${TA}src/lib/tenant-auth.ts`, `${TA}src/lib/validate.ts`, `${TA}test/fakes.ts`, `${TA}test/create-booking.test.ts`, `${TA}test/slots.test.ts`, `${TA}test/tenant-auth.test.ts`, `${TA}package.json`],
    skills: [...W, '1145-tenant-isolation', '1145-conversation-style'],
    goal: 'Keep the core handlers green and finish their TODOs: handoff respects owner availability; knowledge search uses S3 Vectors with the verified filter.',
    testsFirst: ['Handoff outside the owner\'s transfer window returns take_message.', 'searchKnowledge never returns unverified passages to customer-agent (already tested; extend to vector path).', 'Every sayToCaller string passes @1145/conversation-style for voice.'],
    steps: ['Serve repo/fakes change requests from T1–T7 quickly (they cannot edit these files).'],
    acceptance: ['All tool-api tests green; sayToCaller lines natural.'], testCmd: vt(TA) },
  { id: 'T1', title: 'Reschedule and cancel with caller verification', stream: 'tool-api', agent: 'cursor-grok', priority: 1,
    owns: [`${TA}src/handlers/reschedule-booking.ts`, `${TA}src/handlers/cancel-booking.ts`, `${TA}src/lib/booking-lifecycle.ts`, `${TA}src/lib/verification.ts`, `${TA}test/booking-lifecycle.test.ts`],
    skills: [...W, '1145-tenant-isolation'],
    goal: 'Customers can move or cancel bookings safely: caller ID is a hint, not proof.',
    testsFirst: ['customer-agent without verificationCode -> 403 with a natural sayToCaller asking for name + day.', 'issueVerification(callId, bookingId) when name and booked day match; code bound to callId, 10-min TTL.', 'Reschedule moves slot locks atomically (old deleted, new put, one transaction); conflict -> 409.', 'Cancel releases locks, idempotent, emits booking.cancelled.'],
    steps: ['Put DynamoDB access in lib/booking-lifecycle.ts (do not edit repo.ts).'], acceptance: ['Tests green; no tenant id read from body.'], testCmd: vt(TA) },
  { id: 'T2', title: 'Change proposals and confirmation codes', stream: 'tool-api', agent: 'claude', priority: 1,
    owns: [`${TA}src/handlers/admin-propose-change.ts`, `${TA}src/handlers/admin-apply-change.ts`, `${TA}src/lib/changes.ts`, `${TA}test/changes.test.ts`],
    skills: [...W, '1145-tenant-isolation', '1145-conversation-style'],
    goal: 'The admin agent can only propose; the owner applies with a 4-digit code or the dashboard; prices need step-up.',
    testsFirst: ['propose returns a code unique among the tenant\'s open changes, 30-min TTL, and a one-line human summary.', 'apply: owner only; unknown/expired -> 404; price change without valid X-Step-Up-Token -> 428; success emits admin.change_applied and writes audit.', 'admin-agent token calling apply -> 403.'],
    steps: ['Summaries read like a person: "Close Thu Nov 26 for Thanksgiving."'], acceptance: ['Tests green.'], testCmd: vt(TA) },
  { id: 'T3', title: 'Owner reports, bookings list, conversations', stream: 'tool-api', agent: 'cursor-grok', priority: 2,
    owns: [`${TA}src/handlers/admin-summary.ts`, `${TA}src/handlers/admin-list-bookings.ts`, `${TA}src/handlers/admin-list-conversations.ts`, `${TA}src/lib/reports.ts`, `${TA}test/admin-reads.test.ts`],
    skills: [...W, '1145-tenant-isolation'],
    goal: 'Fast, tenant-scoped reads for the copilot and dashboard.',
    testsFirst: ['Date ranges interpreted in the tenant timezone.', 'customer-agent -> 403.', 'Summary counts calls, bookings, messages, minutes, sentiment mix.'],
    steps: ['Query only the tenant partition; paginate.'], acceptance: ['p95 < 300 ms against DynamoDB Local fixture of 5k items.'], testCmd: vt(TA) },
  { id: 'T4', title: 'Owner direct edits: hours and services', stream: 'tool-api', agent: 'cursor-grok', priority: 2,
    owns: [`${TA}src/handlers/admin-update-hours.ts`, `${TA}src/handlers/admin-update-service.ts`, `${TA}src/lib/profile-writes.ts`, `${TA}test/profile-writes.test.ts`],
    skills: [...W, '1145-tenant-isolation'],
    goal: 'Dashboard edits (owner principal only) that re-render the agent so the receptionist knows immediately.',
    testsFirst: ['Only owner/staff principals; admin-agent -> 403.', 'Price change requires step-up token -> 428 otherwise.', 'Successful edit emits admin.change_applied (render-agent subscribes).'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(TA) },
  { id: 'T5', title: 'Resolvers: dialed number and web chat widget key', stream: 'tool-api', agent: 'cursor-grok', priority: 1,
    owns: [`${TA}src/handlers/internal-resolve-number.ts`, `${TA}src/handlers/internal-resolve-widget.ts`, `${TA}src/lib/resolver-deps.ts`, `${TA}test/resolver.test.ts`],
    skills: [...W, '1145-tenant-isolation'],
    goal: 'The voice worker learns the tenant only from the dialed number or the widget key, server-side.',
    testsFirst: ['Unknown number -> 404; suspended tenant -> state suspended; token claims tid/prn=customer-agent/cid/clr.', 'Widget key resolves; disabled widget -> 404; token has ch=webchat and no clr.'],
    steps: ['Read PROFILE.rendered* for agent config; cache 60 s.'], acceptance: ['Tests green; p95 < 100 ms warm.'], testCmd: vt(TA) },
  { id: 'T6', title: 'Rate limiting and abuse guard for the tool API', stream: 'tool-api', agent: 'cursor-grok', priority: 3,
    owns: [`${TA}src/lib/rate-limit.ts`, `${TA}src/lib/http.ts`, `${TA}test/rate-limit.test.ts`],
    skills: [...W, '1145-tenant-isolation'],
    goal: 'One noisy tenant or a looping agent cannot hurt others.',
    testsFirst: ['Token bucket per tenant+principal in DynamoDB; 429 with a natural sayToCaller.', 'handle() applies it before the handler runs.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(TA) },
  { id: 'T7', title: 'Tool API performance and DynamoDB integration', stream: 'tool-api', agent: 'devin', priority: 2,
    owns: [`${TA}src/lib/ddb-repo.ts`, `${TA}src/deps.ts`, `${TA}bench/**`, `${TA}test-integration/**`, 'infra/cdk/lib/api-stack.ts'],
    skills: [...W, '1145-aws-cdk', '1145-tenant-isolation'],
    goal: 'Voice-path tools at p95 ≤ 300 ms in dev, with real DynamoDB and the ABAC role.',
    testsFirst: ['Integration tests against DynamoDB Local for ddb-repo (book transaction, slot conflict, idempotent replay).'],
    steps: ['Benchmark in dev; tune memory, provisioned concurrency, credential caching.', 'Verify AssumeRole+TagSession works in dev and a cross-tenant read is denied by IAM.'],
    acceptance: ['p95 numbers recorded in bench/README.md.'], testCmd: vt(TA) },

  // ───────────────────────────── channels ─────────────────────────────
  { id: 'C1', title: 'Router: identity routes, AgentCore invoke, channel senders', stream: 'channels', agent: 'claude', priority: 1,
    owns: [`${CH}src/router.ts`, `${CH}src/router-deps.ts`, `${CH}src/router-worker.ts`, `${CH}src/lib/**`, `${CH}src/whatsapp-webhook.ts`, `${CH}test/channels.test.ts`, `${CH}package.json`, 'infra/cdk/lib/channels-stack.ts'],
    skills: [...W, '1145-tenant-isolation', '1145-channels-no-approval', '1145-agentcore-agents'],
    goal: 'One router for web chat and Telegram: decides onboarding vs copilot from verified identity, keeps sessions continuous across channels.',
    testsFirst: ['startOnboarding conditional put (two first messages -> one onboarding) and referral recorded.', 'AgentCore invoke with runtimeSessionId = sessionId (min length padding); 25 s timeout sends a natural holding line, then the real reply.', 'webchat replies publish to /owners/<sub>/chat; Telegram replies via telegram-send.'],
    steps: ['Keep WhatsApp code dormant (Phase 2).'], acceptance: ['Replay of the same message id -> one agent invocation.'], testCmd: vt(CH) },
  { id: 'C2', title: 'Telegram bot: webhook, sender, setup script', stream: 'channels', agent: 'cursor-grok', priority: 1,
    owns: [`${CH}src/telegram-send.ts`, `${CH}src/telegram-webhook.ts`, 'scripts/telegram/**', `${CH}test/telegram.test.ts`],
    skills: [...W, '1145-channels-no-approval'],
    goal: 'Owners can onboard and use the copilot in Telegram with zero approvals.',
    testsFirst: ['sendMessage retries 429 honoring retry_after; never retries 4xx.', '/start CODE parsed; group chats ignored.'],
    steps: ['scripts/telegram/set-webhook.ts sets the webhook with secret_token and bot commands (/start, /help).'], acceptance: ['Tests green; script documented.'], testCmd: vt(CH) },
  { id: 'C3', title: 'Owner web chat API', stream: 'channels', agent: 'cursor-grok', priority: 1,
    owns: [`${CH}src/owner-chat.ts`, `${CH}test/owner-chat.test.ts`], skills: [...W, '1145-channels-no-approval', '1145-tenant-isolation'],
    goal: 'The primary owner channel: signed-in web chat, enqueued to the same router.',
    testsFirst: ['Cognito sub from authorizer claims (never body); clientMessageId dedup; referralCode validated.', 'FIFO group = webchat:<sub>.'],
    steps: [], acceptance: ['Returns 202 in < 300 ms.'], testCmd: vt(CH) },
  { id: 'C4', title: 'Customer web chat token endpoint', stream: 'channels', agent: 'cursor-grok', priority: 1,
    owns: [`${CH}src/customer-webchat-token.ts`, `${CH}test/webchat-token.test.ts`], skills: [...W, '1145-channels-no-approval', '1145-voice-livekit'],
    goal: 'A visitor on the tenant\'s website chats with the same receptionist as callers.',
    testsFirst: ['Widget key -> LiveKit token for room chat-<tid>-<uuid> with agent dispatch; unknown key 404; rate limit per IP/key.', 'Token grants only that room, 30-min TTL, no publish of audio.'],
    steps: ['Use livekit-server-sdk AccessToken + RoomConfiguration agents.'], acceptance: ['Tests green.'], testCmd: vt(CH) },
  { id: 'C5', title: 'Referral redirect and attribution', stream: 'channels', agent: 'cursor-grok', priority: 2,
    owns: [`${CH}src/referral-redirect.ts`, `${CH}test/referral.test.ts`], skills: [...W, '1145-channels-no-approval'],
    goal: 'The viral loop is measurable from the first click, without WhatsApp or SMS.',
    testsFirst: ['Valid code -> REFCLICK# counter + 302 to app start URL with ref; invalid -> 302 without ref.', 'Self-referral and repeat clicks do not double count.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(CH) },
  { id: 'C6', title: 'Owner notifications: Telegram, email, web push, urgent call', stream: 'channels', agent: 'devin', priority: 1,
    owns: ['services/notifications/**', 'infra/cdk/lib/notifications-stack.ts'], skills: [...W, '1145-channels-no-approval', '1145-conversation-style'],
    goal: 'Owners hear about bookings, messages and handoffs where they are, written like a person.',
    testsFirst: ['Preference routing per event type; quiet hours; dedupe per event id.', 'Resend email and VAPID push adapters with retries; Telnyx outbound call only for urgent handoff.', 'Every template passes conversation-style (chat).'],
    steps: ['Notification copy examples: "New booking: Tunde, haircut, tomorrow at 3." not "A booking has been created."'],
    acceptance: ['In dev, a test booking reaches Telegram and email within 10 s.'], testCmd: vt('services/notifications') },

  // ───────────────────────────── onboarding ─────────────────────────────
  { id: 'D1', title: 'Onboarding API: basics, waitlist, provisioning start/status', stream: 'onboarding', agent: 'cursor-grok', priority: 1,
    owns: [`${PV}src/api/basics.ts`, `${PV}src/api/waitlist.ts`, `${PV}src/api/provisioning.ts`, `${PV}test/api-core.test.ts`],
    skills: [...W, '1145-provisioning-telnyx'],
    goal: 'The onboarding agent\'s tools have a solid, idempotent backend.',
    testsFirst: ['Service-token auth; onboardingId from path must match token claim.', 'StartExecution name = onboardingId (second call returns existing).', 'Status merges branch states into plain-language progress lines.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(PV) },
  { id: 'D2', title: 'Hours and services parsing with natural read-back', stream: 'onboarding', agent: 'claude', priority: 1,
    owns: [`${PV}src/api/parse-profile.ts`, `${PV}src/lib/profile-parser.ts`, `${PV}test/profile-parser.test.ts`],
    skills: [...W, '1145-conversation-style', '1145-provisioning-telnyx'],
    goal: 'Owners describe hours and services in their own words; we store exact structures and read them back like a person.',
    testsFirst: ['"Tue-Sat 9 to 6, closed Sun Mon" -> BusinessHours; "lunch 12-1" -> split windows; ambiguous input -> a clarifying question, not a guess.', 'Read-back text passes conversation-style (chat).'],
    steps: ['Bedrock call with JSON-only output, schema-validated, one retry with the validation error.'], acceptance: ['20 real-world phrasings in fixtures parse correctly.'], testCmd: vt(PV) },
  { id: 'D3', title: 'Facts review and agent naming', stream: 'onboarding', agent: 'cursor-grok', priority: 1,
    owns: [`${PV}src/api/facts.ts`, `${PV}src/api/agent-name.ts`, `${PV}test/facts.test.ts`], skills: [...W, '1145-provisioning-telnyx'],
    goal: 'Owner decisions complete the waiting workflow steps.',
    testsFirst: ['Approved facts -> verified=true; flagged facts listed first with the reason in plain words.', 'SendTaskSuccess with the stored task token; double submit is harmless.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(PV) },
  { id: 'D4', title: 'Telegram signup link, callback, reverse confirmation', stream: 'onboarding', agent: 'cursor-grok', priority: 2,
    owns: [`${PV}src/api/signup-link.ts`, `${PV}src/api/signup-callback.ts`, `${PV}src/lib/signup-token.ts`, `${PV}test/signup-token.test.ts`, `${PV}test/signup.test.ts`],
    skills: [...W, '1145-tenant-isolation', '1145-channels-no-approval'],
    goal: 'Telegram owners bind a Google identity safely; a forwarded link cannot hijack the account.',
    testsFirst: ['Link response never contains the token; message sent via Telegram sender.', 'Callback consumes once; second account gets "link already used"; binding pending until YES in Telegram.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(PV) },
  { id: 'D5', title: 'Number search, order, engine bind; state machine owner', stream: 'onboarding', agent: 'devin', priority: 1,
    owns: [`${PV}src/steps/search-number.ts`, `${PV}src/steps/bind-engine.ts`, `${PV}src/steps/order-number.ts`, `${PV}src/lib/telnyx.ts`, `${PV}test/order-number.test.ts`, `${PV}test/number.test.ts`, `${PV}package.json`, 'infra/cdk/lib/provisioning-stack.ts'],
    skills: [...W, '1145-provisioning-telnyx', '1145-aws-cdk'],
    goal: 'A working US local number, bound to the voice engine, in under a minute, never bought twice.',
    testsFirst: ['Area code -> state fallback; filters verified against Telnyx API (search is free; record a fixture).', 'bindEngine writes NUMBER# and ENGINEAGENT# routes and assigns the number to the LiveKit connection.'],
    steps: ['Run the state machine end to end in dev with fakes for owner steps.'], acceptance: ['Forced retry of OrderNumber buys one number (test + dev run).'], testCmd: vt(PV) },
  { id: 'D6', title: 'Knowledge scrape with injection flags', stream: 'onboarding', agent: 'cursor-grok', priority: 2,
    owns: [`${PV}src/steps/scrape-knowledge.ts`, `${PV}src/lib/sanitize.ts`, `${PV}test/sanitize.test.ts`, `${PV}test/scrape.test.ts`],
    skills: [...W, '1145-tenant-isolation', '1145-provisioning-telnyx'],
    goal: 'Useful facts from the owner\'s site, stored as unverified data, never as instructions.',
    testsFirst: ['robots.txt respected; max 10 pages, 5 s each, 2 MB total.', 'Instruction-like passages flagged; prices/hours extracted as candidates with source URL.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(PV) },
  { id: 'D7', title: 'Agent templates and render step', stream: 'onboarding', agent: 'claude', priority: 1,
    owns: [`${PV}src/steps/render-agent.ts`, `${PV}src/templates/**`, `${PV}test/render-agent.test.ts`],
    skills: [...W, '1145-conversation-style', '1145-voice-livekit'],
    goal: 'Each tenant\'s receptionist instructions are rendered from a pinned, versioned template that sounds like a real front desk.',
    testsFirst: ['Template v0.1.0 renders business name, services, hours in spoken form, policies from verified facts only.', 'Disclosure line is short and natural and passes conversation-style (voice, first turn).', 'Template versions: canary percentage; tenants pin a version.'],
    steps: ['Write 3 vertical variants (barber/salon, auto repair, home services) that differ in vocabulary, not rules.'], acceptance: ['Eval scenarios pass with the rendered prompts.'], testCmd: vt(PV) },
  { id: 'D8', title: 'Smoke call, activate tenant, await owner, emit status', stream: 'onboarding', agent: 'cursor-grok', priority: 2,
    owns: [`${PV}src/steps/smoke-call.ts`, `${PV}src/steps/activate-tenant.ts`, `${PV}src/steps/await-owner.ts`, `${PV}src/steps/emit-status.ts`, `${PV}test/final-steps.test.ts`],
    skills: [...W, '1145-provisioning-telnyx'],
    goal: 'Finish onboarding cleanly and tell the owner what is happening in plain words.',
    testsFirst: ['Smoke call success = call.ended > 10 s, no error; retry once, then a friendly status and support triage.', 'Activate flips IDENTITY route to the tenant and emits tenant.provisioned.', 'Status messages pass conversation-style (chat).'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(PV) },
  { id: 'D9', title: 'Card on file before buying a number', stream: 'onboarding', agent: 'cursor-grok', priority: 2,
    owns: [`${PV}src/api/payment-setup.ts`, `${PV}src/steps/check-payment-method.ts`, `${PV}test/payment.test.ts`], skills: [...W, '1145-provisioning-telnyx'],
    goal: 'No number is bought for an owner without a card on file (abuse control).',
    testsFirst: ['SetupIntent created for the onboarding customer; step fails NeedsPaymentMethod until attached; emits a friendly status.'],
    steps: ['Stripe test mode in CI.'], acceptance: ['Tests green.'], testCmd: vt(PV) },

  // ───────────────────────────── voice ─────────────────────────────
  { id: 'E1', title: 'LiveKit SIP trunks, dispatch rule, Telnyx connection scripts', stream: 'voice', agent: 'devin', priority: 1,
    owns: ['scripts/livekit/**', 'scripts/telnyx/**', 'infra/cdk/lib/voice-stack.ts', `${FD}Dockerfile`],
    skills: [...W, '1145-voice-livekit', '1145-provisioning-telnyx', '1145-aws-cdk'],
    goal: 'Idempotent scripts create the whole telephony path; the worker deploys to ECS.',
    testsFirst: ['Scripts are idempotent (second run makes no changes) — test with recorded API fixtures.'],
    steps: ['Inbound trunk (all numbers on the connection), dispatch rule individual rooms + agent "frontdesk", outbound trunk with Telnyx credentials.', 'Telnyx FQDN connection to LiveKit SIP and a credential connection for outbound.', 'ECS service: graceful drain on deploy (finish calls).'],
    acceptance: ['A real call to a dev number reaches the worker (with E8).'], testCmd: 'pnpm vitest run scripts' },
  { id: 'E2', title: 'Call events and transcripts', stream: 'voice', agent: 'devin', priority: 1,
    owns: [`${FD}src/frontdesk/events.py`, `${FD}tests/test_events.py`], skills: [...W, '1145-voice-livekit'],
    goal: 'Every call produces live events and a stored transcript the rest of the system relies on.',
    testsFirst: ['call.started/ended envelopes match contracts/events; correlationId = call id.', 'transcript.partial throttled to 2/s; transcript uploaded before call.ended is published.'],
    steps: ['boto3 PutEvents and S3 put; retries; never block the audio path.'], acceptance: ['Tests green; dev call produces both events.'], testCmd: 'cd engines/livekit-agent && uv run pytest -q' },
  { id: 'E3', title: 'Transfers, silence handling, call limits', stream: 'voice', agent: 'devin', priority: 2,
    owns: [`${FD}src/frontdesk/call_control.py`, `${FD}tests/test_call_control.py`], skills: [...W, '1145-voice-livekit', '1145-conversation-style'],
    goal: 'Handoffs to the owner work and awkward silences are handled the way a person would.',
    testsFirst: ['Cold transfer via SIP REFER; failure falls back to take-a-message.', 'Silence: one natural check-in at 8 s, polite close at 20 s; max length 15 min.'],
    steps: ['Warm transfer behind a flag.'], acceptance: ['Real transfer works in dev (with E8).'], testCmd: 'cd engines/livekit-agent && uv run pytest -q' },
  { id: 'E4', title: 'Voice naturalness: prompt, turn-taking, TTS, fillers', stream: 'voice', agent: 'claude', priority: 1,
    owns: [`${FD}src/frontdesk/prompts.py`, `${FD}src/frontdesk/voice_config.py`, `${FD}src/frontdesk/fillers.py`, `${FD}tests/test_naturalness.py`],
    skills: [...W, '1145-conversation-style', '1145-voice-livekit'],
    goal: 'Callers should forget they are talking to software until the disclosure reminds them.',
    testsFirst: ['Fillers never repeat within two uses (exists).', 'Endpointing and interruption values chosen from E8 measurements, documented in voice_config.py.'],
    steps: ['A/B 3 ElevenLabs voices × 2 stability settings on 10 scripted calls; pick by ear with the owner.', 'Pronunciation dictionary for business names (ElevenLabs aliases).'],
    acceptance: ['Eval voice scenarios: zero style errors; owner signs off on two recorded calls.'], testCmd: 'cd engines/livekit-agent && uv run pytest -q' },
  { id: 'E5', title: 'Worker integration and customer web chat (text mode)', stream: 'voice', agent: 'claude', priority: 1,
    owns: [`${FD}src/frontdesk/worker.py`, `${FD}src/frontdesk/agent.py`, `${FD}src/frontdesk/chat.py`, `${FD}src/frontdesk/resolver.py`, `${FD}src/frontdesk/tools_client.py`, `${FD}src/frontdesk/sip.py`, `${FD}src/frontdesk/__init__.py`, `${FD}tests/test_sip.py`, `${FD}tests/test_agent.py`, `${FD}pyproject.toml`],
    skills: [...W, '1145-voice-livekit', '1145-tenant-isolation', '1145-conversation-style'],
    goal: 'One worker, every tenant, phone and web chat, wired to events, call control and the natural voice config.',
    testsFirst: ['Chat rooms resolve via widget key; text mode replies are chat-style (no spoken fillers).', 'Unassigned/suspended paths say natural lines.', 'Pin livekit-agents and plugin versions; fix argument drift.'],
    steps: ['Wire events.turn/ended and call_control from session callbacks.'], acceptance: ['Dev call and dev web chat both book successfully.'], testCmd: 'cd engines/livekit-agent && uv run pytest -q' },
  { id: 'E6', title: 'LiveKit adapter dependencies', stream: 'voice', agent: 'cursor-grok', priority: 2,
    owns: ['engines/livekit-adapter/**'], skills: [...W, '1145-voice-livekit'],
    goal: 'The VoiceEngine implementation for B+ is complete.',
    testsFirst: ['dialOut uses SipClient.createSipParticipant + AgentDispatch; setTenantState flips route state; worker events verified with service token.'],
    steps: [], acceptance: ['Contract tests green.'], testCmd: 'pnpm vitest run engines/livekit-adapter' },
  { id: 'E7', title: 'ElevenAgents fallback adapter verification', stream: 'voice', agent: 'cursor-grok', priority: 4,
    owns: ['engines/elevenlabs-adapter/**'], skills: [...W, '1145-voice-livekit'],
    goal: 'Keep the fallback engine honest against the current ElevenLabs API.',
    testsFirst: ['Recorded-response tests for each VoiceEngine method.'],
    steps: ['Verify endpoint paths against current docs; list differences in the PR.'], acceptance: ['Tests green.'], testCmd: 'pnpm vitest run engines/elevenlabs-adapter' },
  { id: 'E8', title: 'Real-call spike and latency tuning (owner + Devin)', stream: 'voice', agent: 'human', priority: 1,
    owns: ['docs/runbooks/spike-livekit-telnyx-call.md'], skills: [...W, '1145-voice-livekit'],
    goal: 'Real numbers for latency, transfer and concurrency, and a by-ear verdict on how human it sounds.',
    testsFirst: [], steps: ['Follow the runbook with your phone; Devin (E1) has the trunks ready.'],
    acceptance: ['p50/p95 turn latency recorded; 5 concurrent calls; transfer works.'], testCmd: '-' },

  // ───────────────────────────── agents ─────────────────────────────
  { id: 'A1', title: 'AgentCore deploy, memory, runtime plumbing', stream: 'agents', agent: 'devin', priority: 1,
    owns: ['agents/onboarding/app.py', 'agents/admin/app.py', 'agents/common/**', 'agents/deploy/**', 'agents/pyproject.toml'],
    skills: [...W, '1145-agentcore-agents'],
    goal: 'Both chat agents run on AgentCore in dev with short-term memory and continuity across web chat and Telegram.',
    testsFirst: ['Session id stable per onboarding/owner; memory recall test across two invocations.'],
    steps: ['Deploy with the AgentCore starter toolkit; publish ARNs to SSM for the router.'], acceptance: ['Router invokes both runtimes in dev.'], testCmd: 'cd agents && uv run pytest -q' },
  { id: 'A2', title: 'Onboarding conversation quality', stream: 'agents', agent: 'claude', priority: 1,
    owns: ['agents/onboarding/system_prompt.md', 'agents/onboarding/tools.py', 'agents/tests/test_onboarding_tools.py'],
    skills: [...W, '1145-conversation-style', '1145-agentcore-agents'],
    goal: 'Onboarding feels like texting a sharp, friendly person who gets you live in five minutes.',
    testsFirst: ['Tools stay bound to router-supplied ids (exists).', 'Eval scenarios (web + Telegram) pass with zero style errors.'],
    steps: ['Handle skeptics, rushed owners, and "is this a bot?" honestly and warmly.'], acceptance: ['Median onboarding under 12 owner messages in evals.'], testCmd: 'cd agents && uv run pytest -q' },
  { id: 'A3', title: 'Owner copilot conversation quality', stream: 'agents', agent: 'claude', priority: 2,
    owns: ['agents/admin/system_prompt.md', 'agents/admin/tools.py', 'agents/tests/test_admin_tools.py'],
    skills: [...W, '1145-conversation-style', '1145-agentcore-agents', '1145-tenant-isolation'],
    goal: 'The copilot answers like a front-desk manager: answer first, notice what matters, propose changes safely.',
    testsFirst: ['No apply tool; propose relays CONFIRM code (exists).', 'Answer-first replies in evals; no report-speak.'],
    steps: [], acceptance: ['Eval scenarios pass.'], testCmd: 'cd agents && uv run pytest -q' },
  { id: 'A4', title: 'Eval runner, LLM judge, conversation-style gate', stream: 'quality', agent: 'claude', priority: 1,
    owns: ['evals/**', 'packages/conversation-style/**'], skills: [...W, '1145-conversation-style'],
    goal: 'A regression suite that fails CI when any agent starts sounding robotic or breaks a rule.',
    testsFirst: ['Runner executes evals/scenarios/*.yaml against agents with fakes; rule checks + checkReply on every agent turn.', 'LLM judge scores warmness/brevity 1–5; gate >= 4 average.'],
    steps: ['Grow to ≥ 40 scenarios: skeptical caller, interruptions, wrong number, after hours, injection, spoofed caller, small talk, accents (text).'],
    acceptance: ['evals job runs in CI on prompt/template changes.'], testCmd: 'pnpm vitest run packages/conversation-style evals' },

  // ───────────────────────────── post-call ─────────────────────────────
  { id: 'G1', title: 'Conversation analysis with naturalness flags', stream: 'post-call', agent: 'claude', priority: 2,
    owns: [`${PC}src/analyze.ts`, `${PC}test/analyze.test.ts`], skills: [...W, '1145-conversation-style', '1145-tenant-isolation'],
    goal: 'Every real call gets a summary, sentiment, intents, and a naturalness score so we catch robotic turns in production.',
    testsFirst: ['JSON-only Bedrock output, schema-validated; transcript quoted as data (injection test).', 'Naturalness from @1145/conversation-style per agent turn; flagged turns stored for the quality review.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(PC) },
  { id: 'G2', title: 'CRM upsert, usage counter, Stripe usage', stream: 'post-call', agent: 'cursor-grok', priority: 2,
    owns: [`${PC}src/crm.ts`, `${PC}src/usage-store.ts`, `${PC}src/stripe-usage.ts`, `${PC}test/usage-store.test.ts`],
    skills: [...W, '1145-tenant-isolation'],
    goal: 'Customer records and billing stay correct even when events are replayed.',
    testsFirst: ['Upsert merges by phone without overwriting owner edits.', 'Atomic monthly counter; at cap flips route to over_cap and emits tenant.state_changed.', 'Stripe usage idempotency key = callId.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(PC) },
  { id: 'G3', title: 'Post-call handler wiring and infra', stream: 'post-call', agent: 'cursor-grok', priority: 2,
    owns: [`${PC}src/handler.ts`, `${PC}src/usage.ts`, `${PC}src/deps.ts`, `${PC}test/post-call.test.ts`, `${PC}package.json`, 'infra/cdk/lib/postcall-stack.ts'],
    skills: [...W, '1145-aws-cdk'],
    goal: 'call.ended reliably becomes analysis, CRM, usage and live events.',
    testsFirst: ['Replay 3x -> one usage record, one customer update, one live event (extend existing test).'],
    steps: [], acceptance: ['Dev call produces all records.'], testCmd: vt(PC) },

  // ───────────────────────────── control plane ─────────────────────────────
  { id: 'H1', title: 'Stripe webhook, billing state, audit writer', stream: 'control-plane', agent: 'cursor-grok', priority: 2,
    owns: [`${CP}src/stripe.ts`, `${CP}src/stripe-webhook.ts`, `${CP}src/audit.ts`, `${CP}src/set-tenant-state.ts`, `${CP}test/control-plane.test.ts`, `${CP}package.json`],
    skills: [...W, '1145-tenant-isolation'],
    goal: 'Billing drives tenant state deterministically, and every change is audited immutably.',
    testsFirst: ['Webhook verified before parsing; events idempotent by event id.', 'Audit put includes checksum for Object Lock bucket.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(CP) },
  { id: 'H2', title: 'Admin console API and control-plane infra', stream: 'control-plane', agent: 'devin', priority: 3,
    owns: [`${CP}src/console/**`, `${CP}test/console.test.ts`, 'infra/cdk/lib/controlplane-stack.ts'],
    skills: [...W, '1145-tenant-isolation', '1145-aws-cdk'],
    goal: 'The owner\'s React admin console has an API: tenants, usage, suspend/resume, template pinning, export/delete.',
    testsFirst: ['Every write needs reason code + actor; transcripts readable only with a support-case id.'],
    steps: ['IAM-authorized; document endpoints in services/control-plane/README.md for the UI.'], acceptance: ['Tests green; endpoints deployed in dev.'], testCmd: vt(CP) },
  { id: 'H3', title: 'Abuse controls: spam calls, trial caps, referral rewards', stream: 'control-plane', agent: 'cursor-grok', priority: 3,
    owns: [`${CP}src/abuse/**`, `${CP}test/abuse.test.ts`], skills: [...W],
    goal: 'Free minutes and referral rewards cannot be farmed.',
    testsFirst: ['Same caller, < 3 s calls, > N/hour -> blocked for that tenant.', 'Reward only after the referred tenant\'s first paid invoice; one per verified tenant.'],
    steps: [], acceptance: ['Tests green.'], testCmd: vt(CP) },

  // ───────────────────────────── quality ─────────────────────────────
  { id: 'Q1', title: 'Tenant isolation end-to-end in dev', stream: 'quality', agent: 'devin', priority: 2,
    owns: ['tests/e2e/isolation/**'], skills: [...W, '1145-tenant-isolation'],
    goal: 'Prove with real AWS that tenant A can never read tenant B, through any path.',
    testsFirst: ['Token A against every tool route with B ids in body/path -> no B data.', 'Direct AssumeRole with tag A -> DynamoDB query on TENANT#B denied.', 'AppSync subscribe cross-tenant denied.'],
    steps: [], acceptance: ['Runs nightly and after deploys.'], testCmd: 'cd tests/e2e && npm run isolation' },
  { id: 'Q2', title: 'Security threat model and weekly audit', stream: 'quality', agent: 'claude', priority: 3,
    owns: ['docs/security/**', 'docs/checklists/**'], skills: [...W, '1145-tenant-isolation'],
    goal: 'A living threat model and a weekly sweep of merged code against the checklist.',
    testsFirst: [], steps: ['STRIDE per flow; prompt-injection paths; abuse cases; findings filed as issues to owning lanes.'],
    acceptance: ['docs/security/threat-model.md exists and is reviewed weekly.'], testCmd: '-' },

  // ───────────────────────────── UI (you) ─────────────────────────────
  { id: 'U1', title: 'Owner PWA (Flutter web) and admin console (React)', stream: 'ui', agent: 'human', priority: 1,
    owns: ['apps/**'], skills: ['1145-channels-no-approval'],
    goal: 'Built by the owner in parallel; integrates against contracts.',
    testsFirst: [], steps: ['See apps/*/README.md for endpoints and realtime channels.'], acceptance: ['Owner chat, live view, bookings, pending-change confirm, step-up screen.'], testCmd: '-' },
];

export const byId = new Map(ISSUES.map((i) => [i.id, i]));
